# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
 - build
 - test
 - deploy

build:
  image: node:14
  stage: build
  script:
    - npm install @angular/cli@11
    - npm install git
    - npm install
    - git checkout master
    - ng lint
    - ng deploy --repo=https://github.com/reivyn/marvel-database.git