# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
 - test
 - build
 - deploy

build:
  image: node:8
  stage: build
  script:
    - cd packages/public/client/
    - npm install
test:
  stage: test
  script:
    - ng lint

deploy-prod:
  stage: deploy
  script:
    - ng deploy --repo=https://github.com/reivyn/marvel-database.git