build-job:
  stage: build
  script:
    - npm install --silent

test1-job:
  stage: test1
  script:
    - ng lint

deploy-prod:
  stage: deploy
  script:
    - ng deploy --repo=https://github.com/reivyn/marvel-database.git
